### ISSUE TITLE
Wrapper feature not limited to px values

### ISSUE THREAD

**Issue by joerglehmann** [superReal/srgrid#8]
Currently, the wrapper-max-widths can only be *pixel* values.
Ideally, the values can also be %, vw, rem and such.

Example:
`$wrapper-max-widths: (xl: 90vw)`

**Comment by boriskaiser** [comment]
@ingowennemaring / @sergejmueller 
What do you think about this?

**Comment by ingowennemaring** [comment]
I think it would be very helpful and useful.
